services:
  sislogdb:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql_2019
    restart: always
    environment:
      MSSQL_SA_PASSWORD: ${MSSQL_PASS}
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    volumes:
      - ./mssql_data/:/var/opt/mssql/data
      - ./mssql_logs/:/var/opt/mssql/log

  sislogapi:
    image: ${DOCKER_REGISTRY-}sislogapi
    container_name: sislogapi
    build:
      context: ./SisLog
      dockerfile: SisLog.API/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: https://+;http://+
      ASPNETCORE_HTTP_PORTS: ${API_HTTP_PORT}
      ASPNETCORE_HTTPS_PORTS: ${API_HTTPS_PORT}
      ASPNETCORE_Kestrel__Certificates__Default__Password: ${SSL_PASS}
      ASPNETCORE_Kestrel__Certificates__Default__Path: /https/certificate.pfx
      ConnectionStrings__SqlServerConnection: Server=sislogdb;Database=sislogdb;User Id=${MSSQL_USER};Password=${MSSQL_PASS};Encrypt=True;TrustServerCertificate=True;
    volumes:
      - ./certificate.pfx:/https/certificate.pfx
    depends_on:
      - sislogdb
    ports:
      - "${API_HTTP_PORT}:80"
      - "${API_HTTPS_PORT}:443"
